### ISSUE TITLE
Bot is not working

### ISSUE THREAD

**Issue by sergei-bondarenko** [AndrewLaneX/DiscussUnpinBot#12]
@vrumger, @abhint, bot https://t.me/DiscussUnpinBot has stopped working and it is not responding to any commands, could you have a look, please?

**Comment by vrumger** [comment]
Fixed - thanks.

**Comment by sergei-bondarenko** [comment]
@vrumger, it stopped working again :(

**Comment by vrumger** [comment]
@sergei-bondarenko thanks - it's catching up on updates.
