### ISSUE TITLE
[issue] Not working with Pinned Messages 2.0

### ISSUE THREAD

**Issue by HitaloM** [AndrewLaneX/DiscussUnpinBot#6]
After the recent updates of Telegram where were added the [Pinned Messages 2.0](https://t.me/telegram/137) the bot does not seem to be working.

**Comment by vrumger** [comment]
I'll update it when https://github.com/telegraf/telegraf/pull/1173 gets released.

**Comment by HitaloM** [comment]
> I'll update it when https://github.com/telegraf/telegraf/pull/1173 gets released.

Great 😁

**Comment by Laiteux** [comment]
> I'll update it when [telegraf/telegraf#1173](https://github.com/telegraf/telegraf/pull/1173) gets released.

Any ETA on this? Couldn't seem to find one
